"""Template Registry — Phase 11a (Project Creation Scaffolding).

Pure, import-safe definitions of the 10 built-in project templates OSA can
scaffold, plus the helpers that render starter files, ``pyproject.toml`` and
``app.json`` for a new project.

This module is intentionally side-effect free:
    * NO database imports
    * NO filesystem access on import (or anywhere in this module)
    * NO network calls

The orchestration layer (``project_manager.py``) is responsible for actually
writing files to disk, creating venvs and touching the database. This module
only *produces content*.

app.json schema contract
------------------------
The output of :func:`generate_app_json` must match what
``core/app_registry.py::_parse_app_json`` reads. In particular, runtime info
for runnable web/server apps lives under a nested ``web`` block::

    {
        "id": "my-project",
        "name": "My Project",
        "description": "...",
        "icon": "🚀",
        "category": "python",
        "type": "web",             # "web" | "cli" | "other" | ...
        "version": "0.1.0",
        "tags": [...],
        "scripts": [],
        "agent": {...} | null,
        "web": {                    # only for runnable web/server templates
            "command": ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "5200"],
            "port": 5200,
            "venv": ".venv"        # python templates only
        }
    }

``expected_port`` is read by the registry from ``web.port`` — there is NO
top-level ``port`` key.

Templating
----------
File-content templates use ``{{PLACEHOLDER}}`` tokens (NOT ``str.format``),
because the file bodies contain literal ``{`` / ``}`` braces (JSON, JS, JSX)
that would break ``str.format``. Use :func:`render` to substitute tokens.

Supported placeholders: ``PROJECT_NAME``, ``DESCRIPTION``, ``YEAR``, ``PORT``,
``PROJECT_TITLE``.
"""
from __future__ import annotations

import json
import logging

log = logging.getLogger(__name__)

# ── constants ────────────────────────────────────────────────────────────────

DEFAULT_YEAR = "2026"

# Default UV dev-dependencies emitted for every python template.
DEFAULT_DEV_DEPENDENCIES: list[str] = ["pytest", "black", "ruff", "mypy"]

# Python-based template ids. ``fullstack`` is deliberately EXCLUDED here even
# though its backend is python: it is a mixed template whose python code lives
# in a ``backend/`` subfolder, so the "venv at project root" assumption that
# callers make for PYTHON_TEMPLATES does not hold. Callers that need to treat
# the fullstack backend as python must special-case it.
PYTHON_TEMPLATES: set[str] = {"fastapi", "django", "cli"}

# Node-based template ids.
NODE_TEMPLATES: set[str] = {"react", "nextjs", "svelte", "astro", "node-express"}


# ── rendering helpers ────────────────────────────────────────────────────────

def render(text: str, **ctx: str) -> str:
    """Substitute ``{{KEY}}`` tokens in *text* with values from *ctx*.

    Uses plain ``str.replace`` per key so literal ``{`` / ``}`` braces in the
    template body (JSON, JS, JSX) are left untouched. Unknown placeholders in
    *text* are simply left as-is; callers should pass every supported key.
    """
    result = text
    for key, value in ctx.items():
        result = result.replace("{{" + key + "}}", str(value))
    return result


def _title_case(project_name: str) -> str:
    """Turn ``my-cool-project`` into ``My Cool Project``."""
    return project_name.replace("-", " ").replace("_", " ").title()


# ── shared file fragments ────────────────────────────────────────────────────

_PY_GITIGNORE = """# Python
__pycache__/
*.py[cod]
*.egg-info/
.eggs/
build/
dist/
.venv/
venv/
env/
.env
.mypy_cache/
.ruff_cache/
.pytest_cache/
uv.lock
.DS_Store
"""

_NODE_GITIGNORE = """# Node
node_modules/
dist/
build/
.cache/
.env
.env.local
npm-debug.log*
yarn-error.log*
*.log
.DS_Store
"""

_README = """# {{PROJECT_TITLE}}

{{DESCRIPTION}}

## Getting started

See the source files in this project to get going.

---
Scaffolded by AgenticOS · {{YEAR}}
"""


# ── template definitions ─────────────────────────────────────────────────────
# Each template dict carries metadata + a ``files`` map of relative path ->
# content template (with ``{{PLACEHOLDER}}`` tokens). Python templates get their
# ``pyproject.toml`` (re)generated by generate_files; node templates ship a
# tokenised package.json.

TEMPLATES: dict[str, dict] = {
    # ── 1. FastAPI Backend (UV) ──────────────────────────────────────────────
    "fastapi": {
        "name": "FastAPI Backend",
        "description": "Python async API with Pydantic models (UV-powered)",
        "icon": "⚡",
        "category": "python",
        "type": "web",
        "python_version": "3.10+",
        "package_manager": "uv",
        "dependencies": ["fastapi", "uvicorn", "pydantic", "sqlalchemy"],
        "dev_dependencies": DEFAULT_DEV_DEPENDENCIES,
        "web_command": ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "{{PORT}}"],
        "agent": None,
        "files": {
            "README.md": _README,
            ".gitignore": _PY_GITIGNORE,
            "pyproject.toml": "",  # overwritten by generate_pyproject_toml
            "src/__init__.py": "",
            "src/main.py": (
                '"""{{PROJECT_TITLE}} — FastAPI entry point."""\n'
                "from __future__ import annotations\n\n"
                "from fastapi import FastAPI\n\n"
                'app = FastAPI(title="{{PROJECT_TITLE}}", description="{{DESCRIPTION}}")\n\n\n'
                '@app.get("/")\n'
                "def root() -> dict:\n"
                '    return {"app": "{{PROJECT_NAME}}", "status": "ok"}\n\n\n'
                '@app.get("/health")\n'
                "def health() -> dict:\n"
                '    return {"status": "healthy"}\n\n\n'
                'if __name__ == "__main__":\n'
                "    import uvicorn\n\n"
                '    uvicorn.run("src.main:app", host="0.0.0.0", port={{PORT}}, reload=True)\n'
            ),
        },
    },

    # ── 2. Django + REST Framework (UV) ──────────────────────────────────────
    "django": {
        "name": "Django + REST Framework",
        "description": "Full-featured Django API (UV-powered)",
        "icon": "🎸",
        "category": "python",
        "type": "web",
        "python_version": "3.10+",
        "package_manager": "uv",
        "dependencies": ["django", "djangorestframework", "python-dotenv"],
        "dev_dependencies": DEFAULT_DEV_DEPENDENCIES,
        "web_command": ["python", "manage.py", "runserver", "0.0.0.0:{{PORT}}"],
        "agent": None,
        "files": {
            "README.md": _README,
            ".gitignore": _PY_GITIGNORE + "db.sqlite3\n",
            "pyproject.toml": "",  # overwritten by generate_pyproject_toml
            "manage.py": (
                '#!/usr/bin/env python\n'
                '"""Django management entry point for {{PROJECT_TITLE}}."""\n'
                "import os\n"
                "import sys\n\n\n"
                "def main() -> None:\n"
                '    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")\n'
                "    from django.core.management import execute_from_command_line\n\n"
                "    execute_from_command_line(sys.argv)\n\n\n"
                'if __name__ == "__main__":\n'
                "    main()\n"
            ),
            "config/__init__.py": "",
            "config/settings.py": (
                '"""Minimal Django settings for {{PROJECT_TITLE}}."""\n'
                "from pathlib import Path\n\n"
                "BASE_DIR = Path(__file__).resolve().parent.parent\n"
                'SECRET_KEY = "change-me-in-production"\n'
                "DEBUG = True\n"
                'ALLOWED_HOSTS = ["*"]\n\n'
                "INSTALLED_APPS = [\n"
                '    "django.contrib.contenttypes",\n'
                '    "django.contrib.auth",\n'
                '    "rest_framework",\n'
                "]\n\n"
                "MIDDLEWARE = [\n"
                '    "django.middleware.common.CommonMiddleware",\n'
                "]\n\n"
                'ROOT_URLCONF = "config.urls"\n'
                'DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"\n\n'
                "DATABASES = {\n"
                '    "default": {\n'
                '        "ENGINE": "django.db.backends.sqlite3",\n'
                '        "NAME": BASE_DIR / "db.sqlite3",\n'
                "    }\n"
                "}\n"
            ),
            "config/urls.py": (
                '"""URL config for {{PROJECT_TITLE}}."""\n'
                "from django.http import JsonResponse\n"
                "from django.urls import path\n\n\n"
                "def health(request):\n"
                '    return JsonResponse({"status": "healthy", "app": "{{PROJECT_NAME}}"})\n\n\n'
                "urlpatterns = [\n"
                '    path("health/", health),\n'
                "]\n"
            ),
        },
    },

    # ── 3. React + Vite ──────────────────────────────────────────────────────
    "react": {
        "name": "React + Vite",
        "description": "React single-page app with Vite bundler",
        "icon": "⚛️",
        "category": "node",
        "type": "web",
        "node_version": "18+",
        "dependencies": ["react", "react-dom"],
        "dev_dependencies": ["vite", "@vitejs/plugin-react"],
        "web_command": ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "{{PORT}}"],
        "agent": None,
        "files": {
            "README.md": _README,
            ".gitignore": _NODE_GITIGNORE,
            "package.json": (
                "{\n"
                '  "name": "{{PROJECT_NAME}}",\n'
                '  "version": "0.1.0",\n'
                '  "description": "{{DESCRIPTION}}",\n'
                '  "type": "module",\n'
                '  "scripts": {\n'
                '    "dev": "vite",\n'
                '    "build": "vite build",\n'
                '    "preview": "vite preview"\n'
                "  },\n"
                '  "dependencies": {\n'
                '    "react": "^18.2.0",\n'
                '    "react-dom": "^18.2.0"\n'
                "  },\n"
                '  "devDependencies": {\n'
                '    "@vitejs/plugin-react": "^4.2.0",\n'
                '    "vite": "^5.0.0"\n'
                "  }\n"
                "}\n"
            ),
            "vite.config.js": (
                "import { defineConfig } from 'vite'\n"
                "import react from '@vitejs/plugin-react'\n\n"
                "export default defineConfig({\n"
                "  plugins: [react()],\n"
                "  server: { host: '0.0.0.0', port: {{PORT}} },\n"
                "})\n"
            ),
            "index.html": (
                "<!doctype html>\n"
                '<html lang="en">\n'
                "  <head>\n"
                '    <meta charset="UTF-8" />\n'
                '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
                "    <title>{{PROJECT_TITLE}}</title>\n"
                "  </head>\n"
                "  <body>\n"
                '    <div id="root"></div>\n'
                '    <script type="module" src="/src/main.jsx"></script>\n'
                "  </body>\n"
                "</html>\n"
            ),
            "src/main.jsx": (
                "import React from 'react'\n"
                "import ReactDOM from 'react-dom/client'\n"
                "import App from './App.jsx'\n\n"
                "ReactDOM.createRoot(document.getElementById('root')).render(\n"
                "  <React.StrictMode>\n"
                "    <App />\n"
                "  </React.StrictMode>,\n"
                ")\n"
            ),
            "src/App.jsx": (
                "export default function App() {\n"
                "  return (\n"
                "    <main>\n"
                "      <h1>{{PROJECT_TITLE}}</h1>\n"
                "      <p>{{DESCRIPTION}}</p>\n"
                "    </main>\n"
                "  )\n"
                "}\n"
            ),
        },
    },

    # ── 4. Next.js ───────────────────────────────────────────────────────────
    "nextjs": {
        "name": "Next.js",
        "description": "React framework with App Router and API routes",
        "icon": "▲",
        "category": "node",
        "type": "web",
        "node_version": "18+",
        "dependencies": ["next", "react", "react-dom"],
        "dev_dependencies": [],
        "web_command": ["npm", "run", "dev", "--", "--port", "{{PORT}}"],
        "agent": None,
        "files": {
            "README.md": _README,
            ".gitignore": _NODE_GITIGNORE + ".next/\n",
            "package.json": (
                "{\n"
                '  "name": "{{PROJECT_NAME}}",\n'
                '  "version": "0.1.0",\n'
                '  "description": "{{DESCRIPTION}}",\n'
                '  "scripts": {\n'
                '    "dev": "next dev",\n'
                '    "build": "next build",\n'
                '    "start": "next start"\n'
                "  },\n"
                '  "dependencies": {\n'
                '    "next": "^14.0.0",\n'
                '    "react": "^18.2.0",\n'
                '    "react-dom": "^18.2.0"\n'
                "  }\n"
                "}\n"
            ),
            "next.config.js": (
                "/** @type {import('next').NextConfig} */\n"
                "const nextConfig = {}\n\n"
                "module.exports = nextConfig\n"
            ),
            "app/page.jsx": (
                "export default function Home() {\n"
                "  return (\n"
                "    <main>\n"
                "      <h1>{{PROJECT_TITLE}}</h1>\n"
                "      <p>{{DESCRIPTION}}</p>\n"
                "    </main>\n"
                "  )\n"
                "}\n"
            ),
            "app/layout.jsx": (
                "export const metadata = {\n"
                "  title: '{{PROJECT_TITLE}}',\n"
                "  description: '{{DESCRIPTION}}',\n"
                "}\n\n"
                "export default function RootLayout({ children }) {\n"
                "  return (\n"
                '    <html lang="en">\n'
                "      <body>{children}</body>\n"
                "    </html>\n"
                "  )\n"
                "}\n"
            ),
            "app/api/health/route.js": (
                "export function GET() {\n"
                "  return Response.json({ status: 'healthy', app: '{{PROJECT_NAME}}' })\n"
                "}\n"
            ),
        },
    },

    # ── 5. Svelte + Vite ─────────────────────────────────────────────────────
    "svelte": {
        "name": "Svelte + Vite",
        "description": "Svelte single-page app with Vite bundler",
        "icon": "🔥",
        "category": "node",
        "type": "web",
        "node_version": "18+",
        "dependencies": ["svelte"],
        "dev_dependencies": ["vite", "@sveltejs/vite-plugin-svelte"],
        "web_command": ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "{{PORT}}"],
        "agent": None,
        "files": {
            "README.md": _README,
            ".gitignore": _NODE_GITIGNORE,
            "package.json": (
                "{\n"
                '  "name": "{{PROJECT_NAME}}",\n'
                '  "version": "0.1.0",\n'
                '  "description": "{{DESCRIPTION}}",\n'
                '  "type": "module",\n'
                '  "scripts": {\n'
                '    "dev": "vite",\n'
                '    "build": "vite build",\n'
                '    "preview": "vite preview"\n'
                "  },\n"
                '  "dependencies": {\n'
                '    "svelte": "^4.2.0"\n'
                "  },\n"
                '  "devDependencies": {\n'
                '    "@sveltejs/vite-plugin-svelte": "^3.0.0",\n'
                '    "vite": "^5.0.0"\n'
                "  }\n"
                "}\n"
            ),
            "vite.config.js": (
                "import { defineConfig } from 'vite'\n"
                "import { svelte } from '@sveltejs/vite-plugin-svelte'\n\n"
                "export default defineConfig({\n"
                "  plugins: [svelte()],\n"
                "  server: { host: '0.0.0.0', port: {{PORT}} },\n"
                "})\n"
            ),
            "index.html": (
                "<!doctype html>\n"
                '<html lang="en">\n'
                "  <head>\n"
                '    <meta charset="UTF-8" />\n'
                "    <title>{{PROJECT_TITLE}}</title>\n"
                "  </head>\n"
                "  <body>\n"
                '    <script type="module" src="/src/main.js"></script>\n'
                "  </body>\n"
                "</html>\n"
            ),
            "src/main.js": (
                "import App from './App.svelte'\n\n"
                "const app = new App({ target: document.body })\n\n"
                "export default app\n"
            ),
            "src/App.svelte": (
                "<script>\n"
                "  const title = '{{PROJECT_TITLE}}'\n"
                "</script>\n\n"
                "<main>\n"
                "  <h1>{title}</h1>\n"
                "  <p>{{DESCRIPTION}}</p>\n"
                "</main>\n"
            ),
        },
    },

    # ── 6. Astro ─────────────────────────────────────────────────────────────
    "astro": {
        "name": "Astro",
        "description": "Content-focused site with Astro and API routes",
        "icon": "🚀",
        "category": "node",
        "type": "web",
        "node_version": "18+",
        "dependencies": ["astro"],
        "dev_dependencies": [],
        "web_command": ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "{{PORT}}"],
        "agent": None,
        "files": {
            "README.md": _README,
            ".gitignore": _NODE_GITIGNORE + ".astro/\n",
            "package.json": (
                "{\n"
                '  "name": "{{PROJECT_NAME}}",\n'
                '  "version": "0.1.0",\n'
                '  "description": "{{DESCRIPTION}}",\n'
                '  "type": "module",\n'
                '  "scripts": {\n'
                '    "dev": "astro dev",\n'
                '    "build": "astro build",\n'
                '    "preview": "astro preview"\n'
                "  },\n"
                '  "dependencies": {\n'
                '    "astro": "^4.0.0"\n'
                "  }\n"
                "}\n"
            ),
            "astro.config.mjs": (
                "import { defineConfig } from 'astro/config'\n\n"
                "export default defineConfig({\n"
                "  server: { host: '0.0.0.0', port: {{PORT}} },\n"
                "})\n"
            ),
            "src/pages/index.astro": (
                "---\n"
                "const title = '{{PROJECT_TITLE}}'\n"
                "---\n"
                "<html lang=\"en\">\n"
                "  <head><title>{title}</title></head>\n"
                "  <body>\n"
                "    <h1>{title}</h1>\n"
                "    <p>{{DESCRIPTION}}</p>\n"
                "  </body>\n"
                "</html>\n"
            ),
            "src/pages/api/health.js": (
                "export function GET() {\n"
                "  return new Response(\n"
                "    JSON.stringify({ status: 'healthy', app: '{{PROJECT_NAME}}' }),\n"
                "    { headers: { 'Content-Type': 'application/json' } }\n"
                "  )\n"
                "}\n"
            ),
        },
    },

    # ── 7. Node.js + Express ─────────────────────────────────────────────────
    "node-express": {
        "name": "Node.js + Express",
        "description": "Express HTTP API server",
        "icon": "🟢",
        "category": "node",
        "type": "web",
        "node_version": "18+",
        "dependencies": ["express", "dotenv", "cors"],
        "dev_dependencies": [],
        "web_command": ["node", "src/server.js"],
        "agent": None,
        "files": {
            "README.md": _README,
            ".gitignore": _NODE_GITIGNORE,
            "package.json": (
                "{\n"
                '  "name": "{{PROJECT_NAME}}",\n'
                '  "version": "0.1.0",\n'
                '  "description": "{{DESCRIPTION}}",\n'
                '  "type": "commonjs",\n'
                '  "main": "src/server.js",\n'
                '  "scripts": {\n'
                '    "start": "node src/server.js",\n'
                '    "dev": "node src/server.js"\n'
                "  },\n"
                '  "dependencies": {\n'
                '    "cors": "^2.8.5",\n'
                '    "dotenv": "^16.3.0",\n'
                '    "express": "^4.18.0"\n'
                "  }\n"
                "}\n"
            ),
            "src/server.js": (
                "const express = require('express')\n"
                "const cors = require('cors')\n"
                "require('dotenv').config()\n\n"
                "const app = express()\n"
                "const PORT = process.env.PORT || {{PORT}}\n\n"
                "app.use(cors())\n"
                "app.use(express.json())\n\n"
                "app.get('/', (req, res) => {\n"
                "  res.json({ app: '{{PROJECT_NAME}}', status: 'ok' })\n"
                "})\n\n"
                "app.get('/health', (req, res) => {\n"
                "  res.json({ status: 'healthy' })\n"
                "})\n\n"
                "app.listen(PORT, '0.0.0.0', () => {\n"
                "  console.log(`{{PROJECT_TITLE}} listening on port ${PORT}`)\n"
                "})\n"
            ),
        },
    },

    # ── 8. Full-Stack (FastAPI + React) ──────────────────────────────────────
    "fullstack": {
        "name": "Full-Stack (FastAPI + React)",
        "description": "FastAPI backend (UV) with a React + Vite frontend",
        "icon": "🧩",
        "category": "fullstack",
        "type": "web",
        "python_version": "3.10+",
        "node_version": "18+",
        "package_manager": "uv",
        "dependencies": ["fastapi", "uvicorn", "pydantic"],
        "dev_dependencies": DEFAULT_DEV_DEPENDENCIES,
        # Backend is the runnable web service; venv lives under backend/.
        "web_command": [
            "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "{{PORT}}",
        ],
        "agent": None,
        "files": {
            "README.md": _README + (
                "\n## Layout\n\n"
                "- `backend/` — FastAPI service (UV-managed)\n"
                "- `frontend/` — React + Vite app\n"
            ),
            ".gitignore": _PY_GITIGNORE + _NODE_GITIGNORE,
            "docker-compose.yml": (
                "version: '3.9'\n"
                "services:\n"
                "  backend:\n"
                "    build: ./backend\n"
                '    ports: ["{{PORT}}:{{PORT}}"]\n'
                "  frontend:\n"
                "    build: ./frontend\n"
            ),
            "backend/pyproject.toml": "",  # (re)generated below via generate_pyproject_toml
            "backend/src/__init__.py": "",
            "backend/src/main.py": (
                '"""{{PROJECT_TITLE}} — FastAPI backend."""\n'
                "from __future__ import annotations\n\n"
                "from fastapi import FastAPI\n\n"
                'app = FastAPI(title="{{PROJECT_TITLE}}", description="{{DESCRIPTION}}")\n\n\n'
                '@app.get("/api/health")\n'
                "def health() -> dict:\n"
                '    return {"status": "healthy", "app": "{{PROJECT_NAME}}"}\n'
            ),
            "frontend/package.json": (
                "{\n"
                '  "name": "{{PROJECT_NAME}}-frontend",\n'
                '  "version": "0.1.0",\n'
                '  "description": "{{DESCRIPTION}}",\n'
                '  "type": "module",\n'
                '  "scripts": {\n'
                '    "dev": "vite",\n'
                '    "build": "vite build"\n'
                "  },\n"
                '  "dependencies": {\n'
                '    "react": "^18.2.0",\n'
                '    "react-dom": "^18.2.0"\n'
                "  },\n"
                '  "devDependencies": {\n'
                '    "@vitejs/plugin-react": "^4.2.0",\n'
                '    "vite": "^5.0.0"\n'
                "  }\n"
                "}\n"
            ),
            "frontend/src/App.jsx": (
                "export default function App() {\n"
                "  return (\n"
                "    <main>\n"
                "      <h1>{{PROJECT_TITLE}}</h1>\n"
                "      <p>{{DESCRIPTION}}</p>\n"
                "    </main>\n"
                "  )\n"
                "}\n"
            ),
        },
    },

    # ── 9. Python CLI Tool (UV) ──────────────────────────────────────────────
    "cli": {
        "name": "Python CLI Tool",
        "description": "Command-line tool built with Typer (UV-powered)",
        "icon": "🖥️",
        "category": "python",
        "type": "cli",
        "python_version": "3.10+",
        "package_manager": "uv",
        "dependencies": ["click", "typer"],
        "dev_dependencies": DEFAULT_DEV_DEPENDENCIES,
        "web_command": None,  # CLI tools are not runnable web services
        "agent": None,
        "files": {
            "README.md": _README,
            ".gitignore": _PY_GITIGNORE,
            "pyproject.toml": "",  # overwritten by generate_pyproject_toml
            "src/__init__.py": "",
            "src/cli.py": (
                '"""{{PROJECT_TITLE}} — command-line interface."""\n'
                "from __future__ import annotations\n\n"
                "import typer\n\n"
                'app = typer.Typer(help="{{DESCRIPTION}}")\n\n\n'
                '@app.command()\n'
                'def hello(name: str = "world") -> None:\n'
                '    """Say hello."""\n'
                '    typer.echo(f"Hello, {name}! — from {{PROJECT_NAME}}")\n\n\n'
                'if __name__ == "__main__":\n'
                "    app()\n"
            ),
        },
    },

    # ── 10. Monorepo (empty structure) ───────────────────────────────────────
    "monorepo": {
        "name": "Monorepo",
        "description": "Empty monorepo structure — bring your own apps/services",
        "icon": "📦",
        "category": "other",
        "type": "other",
        "dependencies": [],
        "dev_dependencies": [],
        "web_command": None,
        "agent": None,
        "files": {
            "README.md": _README + (
                "\n## Structure\n\n"
                "- `apps/` — application code\n"
                "- `packages/` — shared libraries\n"
                "- `services/` — backend services\n"
            ),
            ".gitignore": _NODE_GITIGNORE + "__pycache__/\n.venv/\n",
            "apps/.gitkeep": "",
            "packages/.gitkeep": "",
            "services/.gitkeep": "",
        },
    },
}


# ── public API ────────────────────────────────────────────────────────────────

def get_template(name: str) -> dict:
    """Return the template definition for *name*.

    Raises:
        ValueError: if *name* is not a known template id.
    """
    if name not in TEMPLATES:
        raise ValueError(
            f"Unknown template: {name!r}. Valid templates: {sorted(TEMPLATES)}"
        )
    return TEMPLATES[name]


def generate_pyproject_toml(
    project_name: str,
    description: str,
    dependencies: list[str],
    dev_dependencies: list[str] | None = None,
) -> str:
    """Render a valid UV-compatible ``pyproject.toml``.

    Dependency entries are emitted as bare, valid PEP 508 requirement strings —
    just the package name (e.g. ``"fastapi"``). We deliberately do NOT append a
    dangling version operator like ``"fastapi>="`` (which is invalid PEP 508 and
    breaks ``uv``); ``uv`` will resolve the latest compatible version and pin it
    in ``uv.lock``.
    """
    if dev_dependencies is None:
        dev_dependencies = DEFAULT_DEV_DEPENDENCIES

    desc = description or f"A Codehome project ({project_name})"

    def _fmt(items: list[str]) -> str:
        if not items:
            return ""
        return "\n" + "\n".join(f'    "{item}",' for item in items) + "\n"

    deps_block = _fmt(dependencies)
    dev_block = _fmt(dev_dependencies)

    return (
        "[project]\n"
        f'name = "{project_name}"\n'
        'version = "0.1.0"\n'
        f'description = "{desc}"\n'
        'requires-python = ">=3.10"\n'
        f"dependencies = [{deps_block}]\n"
        "\n"
        "[build-system]\n"
        'requires = ["hatchling"]\n'
        'build-backend = "hatchling.build"\n'
        "\n"
        "[tool.uv]\n"
        f"dev-dependencies = [{dev_block}]\n"
    )


def generate_app_json(
    project_name: str,
    template: str,
    port: int,
    description: str,
) -> dict:
    """Build an ``app.json`` dict matching the app_registry schema.

    Web/server + frontend templates get a nested ``web`` block with the resolved
    run command (with the real *port* substituted), ``port`` and — for python
    templates — ``venv=".venv"``. CLI templates use ``type="cli"`` and no web
    block. ``monorepo`` is minimal with ``type="other"``.
    """
    tpl = get_template(template)
    desc = description or f"A {template} project"

    app: dict = {
        "id": project_name,
        "name": _title_case(project_name),
        "description": desc,
        "icon": tpl.get("icon", "📦"),
        "category": tpl.get("category", "other"),
        "type": tpl.get("type", "web"),
        "version": "0.1.0",
        "tags": [template],
        "scripts": [],
        "agent": tpl.get("agent"),
    }

    web_command_tpl = tpl.get("web_command")
    tpl_type = tpl.get("type", "web")

    # Only runnable web services get a web block: a resolved command + port.
    if web_command_tpl and tpl_type not in ("cli", "other"):
        command = [render(part, PORT=str(port)) for part in web_command_tpl]
        web: dict = {"command": command, "port": port}
        # venv only makes sense for python-based runnable templates.
        if template in PYTHON_TEMPLATES or tpl.get("package_manager") == "uv":
            web["venv"] = ".venv"
        app["web"] = web

    return app


def generate_files(
    template_name: str,
    project_name: str,
    description: str,
    port: int,
) -> dict[str, str]:
    """Render every file for *template_name* into ``{relative_path: content}``.

    Steps:
        1. Render each ``files`` entry via :func:`render`, substituting all
           supported placeholders.
        2. For python templates, (re)generate ``pyproject.toml`` from
           :func:`generate_pyproject_toml`. For ``fullstack``, the backend
           ``backend/pyproject.toml`` is generated instead.
        3. Add ``app.json`` as ``json.dumps(generate_app_json(...), indent=2)``.

    No ``{{...}}`` tokens remain in the returned content.
    """
    tpl = get_template(template_name)
    desc = description or "A Codehome project"
    ctx = {
        "PROJECT_NAME": project_name,
        "PROJECT_TITLE": _title_case(project_name),
        "DESCRIPTION": desc,
        "YEAR": DEFAULT_YEAR,
        "PORT": str(port),
    }

    files: dict[str, str] = {}
    for rel_path, content in tpl["files"].items():
        files[rel_path] = render(content, **ctx)

    # (Re)generate pyproject.toml for python-based templates.
    pyproject = generate_pyproject_toml(
        project_name=project_name,
        description=desc,
        dependencies=tpl.get("dependencies", []),
        dev_dependencies=tpl.get("dev_dependencies"),
    )
    if template_name in PYTHON_TEMPLATES:
        files["pyproject.toml"] = pyproject
    elif template_name == "fullstack":
        # Mixed template: python lives under backend/.
        files["backend/pyproject.toml"] = generate_pyproject_toml(
            project_name=f"{project_name}-backend",
            description=desc,
            dependencies=tpl.get("dependencies", []),
            dev_dependencies=tpl.get("dev_dependencies"),
        )

    # app.json (canonical registry metadata).
    files["app.json"] = json.dumps(
        generate_app_json(project_name, template_name, port, description),
        indent=2,
    )

    return files
